
var keyMirror = require('keymirror');

module.exports = keyMirror({
  BLOGPOST_DELETE_LOADING: null,
  BLOGPOST_DELETE_FINISHED: null,
  BLOGPOST_DELETE_ERROR: null,
  BLOGPOST_LOAD_LOADING: null,
  BLOGPOST_LOAD_FINISHED: null,
  BLOGPOST_LOAD_ERROR: null,
  BLOGPOST_CREATE_LOADING: null,
  BLOGPOST_CREATE_FINISHED: null,
  BLOGPOST_CREATE_ERROR: null,
  BLOGPOST_EDIT_LOADING: null,
  BLOGPOST_EDIT_FINISHED: null,
  BLOGPOST_EDIT_ERROR: null,

});
